# 此工作流将安装 Python 依赖项、运行测试并使用单一版本的 Python 执行 lint
# 更多信息参见：https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automatically clock in

on:
#   push:
#     branches:
#       - main
  schedule:
    - cron: '10 * * * *' #每个小时的15分钟启动工作流， minute (0 - 59) hour (0 - 23) day of the month (1 - 31) month (1 - 12 or JAN-DEC)day of the week (0 - 6 or SUN-SAT)
  workflow_dispatch:
#   watch:
#     types: started
#   repository_dispatch:
#     types: node

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install datetime
        pip install pytz
        pip install playwright==1.14.1
        python -m playwright install chromium
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: auto_clock_in
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        NAME: ${{ secrets.NAME }}
        EMAIL: ${{ secrets.EMAIL }}
      run: |
        python clock_in.py $USERNAME $PASSWORD $NAME $EMAIL
        dir
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional, but recommended
        # Defaults to "Apply automatic changes"
        commit_message: Automated Change
        
    
